development:
  adapter: postgresql
  encoding: unicode
  database: ember-rails-blog_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ember-rails-blog_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ember-rails-blog_production
  pool: 5
  host: localhost
